module.exports = {
    EXCHANGE_LOCK_CURRENCY: 130,
    EXCHANGE_MATCH_ORDER: 131,
    EXCHANGE_CLOSE_ORDER: 132,
    EXCHANGE_FEE: 133,
    EXCHANGE_SWAP: 134,
    EXCHANGE_SWAP_FEE: 135,
    EXCHANGE_SWAP_FIXED_FEE: 136,

    // SPOT
    SPOT_COMMISSION: 800,

    // PARTNER_ORDER
    PARTNER_TRANSACTION: 200,
}
