'use strict'

const Model = use('Model')

class TransactionHistory extends Model {
}

module.exports = TransactionHistory

TransactionHistory.Category = {
    ROLLBACK_WALLET: 0,
    ORDER_REQUIRED_MARGIN: 1,
    ORDER_CLOSE_ORDER_MARGIN_BACK: 2,
    ORDER_CLOSE_PROFIT: 3,
    DEPOSIT: 4,
    WITHDRAW: 5,
    ORDER_MODIFY_NAC_BET: 6,
    ORDER_FEE_REFER: 7,

    MONEY_REVERSE_MULTI_CLOSE: 20,
    ORDER_MULTI_CLOSE_REVERSED: 21,

    ORDER_WITHDRAW_NLF_REVENUE: 26,

    EXCHANGE_PLACE_SELL: 30,
    EXCHANGE_CLOSE_SELL: 31,
    EXCHANGE_RETURN_NAC: 32,
    MATCH_SELL_SPIN: 33,

    COINBASE_DEPOSIT_BTC: 36,
    INTERNAL_BUY_SPIN: 37,
    PROMOTE_COINBASE_BUY_SPIN: 38,
    COINBASE_DEPOSIT_ETH: 39,
    EXCHANGE_BUY_SPIN: 40,
    EXCHANGE_SPEND_SPIN: 41,
    TRANSFER_SPIN: 42,
    TRANSFER_NAC: 43,
    TRANSFER_WALLET_TOKEN: 44,
    BUY_ETH_FROM_ROOT: 45,

    TRANSFER_WALLET: 48,
    TRANSFER_ON_RESET: 50,

    WITHDRAW_REFER_NAC_MONEY: 60,

    SPIN_RIGHT_PRIZE: 61,

    CONVERT_TOKEN_TO_ETH_DEDUCTION: 70,
    CONVERT_TOKEN_TO_ETH_RECEIVED: 71,

    CHALLENGE_BET_TOKEN: 80,
    CHALLENGE_UNLOCK_TOKEN: 81,
    CHALLENGE_UPDATE_BET_TOKEN: 82,
    CHALLENGE_REWARD: 83,
    CHALLENGE_CUSTOM_REWARD: 84,
    CHALLENGE_ALTCOIN_REWARD: 85,
    CHALLENGE_RACING_REWARD: 86,
    CHALLENGE_SURVIVAL_REWARD: 87,
    CHALLENGE_1E_REWARD: 88,
    CHALLENGE_SURVIVAL_REWARD_HOST: 89,
    CHALLENGE_SURVIVAL_UNLOCK_BET_TOKEN: 79,

    FEE_CONVERT_TOKEN: 90,
    FEE_WITHDRAW: 91,
    FEE_DEPOSIT: 92,

    FEE_EXCHANGE_SPIN: 93,

    DEPOSIT_REBATE: 95,

    CAMPAIGN_BONUS_FREE_TURN: 99,
    CAMPAIGN_ON_TURN: 100,
    BUY_TURN: 101,
    CAMPAIGN_REWARD: 102,
    CAMPAIGN_BONUS_TURN: 103,
    CAMPAIGN_TURN_ROLLBACK: 104,

    // NAMI EXCHANGE
    EXCHANGE_LOCK_CURRENCY: 130,
    EXCHANGE_MATCH_ORDER: 131,
    EXCHANGE_CLOSE_ORDER: 132,
    EXCHANGE_FEE: 133,

    // SPIN Launch pad
    LAUNCHPAD_BUY_AND_LOCK: 140,
    LAUNCHPAD_UNLOCK: 141,
    LAUNCH_PAD_REGISTER_IEO_BONUS: 142,
    LAUNCH_PAD_REGISTER_LOCK: 143,
    LAUNCH_PAD_BONUS_BUY: 144,
    LAUNCH_PAD_UNLOCK_BONUS_BUY: 145,

    CHANGE_BALANCE_ROOT_WALLET: 990,
    CHANGE_BALANCE_BURN_WALLET: 991,
    CHANGE_BALANCE_CUSTOMER_WALLET: 992,
    CHANGE_BALANCE_EXCHANGE_WALLET: 993,
    CHANGE_BALANCE_EXCHANGE_FEE_WALLET: 994,

    // ERC20
    DEPOSIT_ERC20_BNB: 150,
    DEPOSIT_ERC20_MKR: 151,
    DEPOSIT_ERC20_BAT: 152,
    DEPOSIT_ERC20_OMG: 153,
    DEPOSIT_ERC20_LINK: 154,
    DEPOSIT_ERC20_HOT: 155,
    DEPOSIT_ERC20_ZIL: 156,
    DEPOSIT_ERC20_REP: 157,
    DEPOSIT_ERC20_ZRX: 158,
    DEPOSIT_ERC20_THETA: 159,
    DEPOSIT_ERC20_NPXS: 160,
    DEPOSIT_ERC20_IOST: 161,
    DEPOSIT_ERC20_ENJ: 162,
    DEPOSIT_ERC20_HT: 163,
    DEPOSIT_ERC20_SNT: 164,
    DEPOSIT_ERC20_DAI: 165,
    DEPOSIT_ERC20_KNC: 166,

    DEPOSIT_ERC20_GNT: 167,
    DEPOSIT_ERC20_PPT: 168,
    DEPOSIT_ERC20_MCO: 169,
    DEPOSIT_ERC20_WTC: 170,
    DEPOSIT_ERC20_MANA: 171,
    DEPOSIT_ERC20_LOOM: 172,
    DEPOSIT_ERC20_LRC: 173,
    DEPOSIT_ERC20_ELF: 174,
    DEPOSIT_ERC20_POWR: 175,
    DEPOSIT_ERC20_USDC: 176,
    DEPOSIT_ERC20_USDT: 177,
    DEPOSIT_ERC20_FET: 178,
    DEPOSIT_ERC20_CELR: 179,
    DEPOSIT_ERC20_BLOC: 180,
    DEPOSIT_ERC20_DOS: 181,
    DEPOSIT_ERC20_NAMI: 182,
    DEPOSIT_ERC20_SPIN: 183,
    DEPOSIT_ERC20_MATIC: 184,
    DEPOSIT_ERC20_MITH: 185,
    DEPOSIT_ERC20_GTO: 186,

    // Refer
    LAUNCHPAD_REFER_LV_1: 400,
    LAUNCHPAD_REFER_LV_2: 401,
    COMMON_REFER_LV_1: 402,
    COMMON_REFER_LV_2: 403,

    BUY_BACK: 410,
    BATCH_DEPOSIT: 415,

    // Buy back BNB
    BUY_BACK_LOAN_FEE: 500,
    BUY_BACK_REGISTER_SELL: 501,
    BUY_BACK_PROFIT_USE_LOAN: 502,
    BUY_BACK_PROFIT_USE_MAIN: 503,

    BUY_BACK_REGISTER_HOLD: 504,

    // Future 600-700
    FUTURE_PLACE_ORDER_FEE: 600,
    FUTURE_PLACE_ORDER_MARGIN: 601,
    FUTURE_CLOSE_ORDER_PROFIT: 602,
    FUTURE_SWAP: 603,
    FUTURE_SWAP_V2: 610,
    FUTURE_REFERRAL_COMMISION: 604,
    FUTURE_VNDC_FEE_PROMOTE: 605,
    FUTURE_VNDC_LIQUIDATE_FEE: 606,
    FUTURE_FUNDING_FEE: 611,
    FUTURE_REWARD: 612,
    FUTURE_PLACE_ORDER_LOAN_FEE: 620,
    FUTURE_PLACE_ORDER_LOAN_MARGIN: 621,
    FUTURE_CLOSE_ORDER_LOAN_PROFIT: 622,
    FUTURE_LOAN_LIQUIDATE_FEE: 623,
    FUTURE_LIQUIDATION_LOAN_VALUE: 624,
    FUTURE_PLACE_ORDER_LOAN_MAINTENANCE_MARGIN: 625,
    FUTURE_LOAN_FUNDING_FEE: 626,
    FUTURE_SHARE_TO_MASTER: 630,

    LOAN: 810,
    LOAN_FUNDING: 811,

    // Air drop
    AIR_DROP_1508: 1000
}

TransactionHistory.Status = {
    NONE: 0,

    // Withdraw
    WITHDRAW_WAITING: 1,
    WITHDRAW_DONE: 2,
    WITHDRAW_REJECTED: 3,
    WITHDRAW_TRANSFER_BACK: 4,
    WITHDRAW_TX_PENDING: 5,
    WITHDRAW_ETH_WAITING: 11,
    WITHDRAW_ETH_DONE: 12,
    WITHDRAW_ETH_REJECTED: 13,
    WITHDRAW_ETH_TRANSFER_BACK: 14,
    WITHDRAW_ETH_TX_PENDING: 15
}
